apiVersion: v2
name: mam
description: A Helm chart for Kubernetes
type: application
version: 0.1.5
appVersion: "0.0.2"
dependencies:
- name: nginx
  version: "9.4.2"
  repository: "https://charts.bitnami.com/bitnami"