name: app1-stage
image:
  name: jkosik/app1
  tag: stage

#subchart
nginx:
  name: app1-stage-subchart
  image:
    name: nginx
    tag: 1.21.0

# dependency
haproxy:
  nameOverride: haproxy-stage-dependency
